name: 'sf_pipeline'
version: '1.0.0'

profile: 'sf_pipeline'

model-paths: ['models']
seed-paths: ['seeds']
test-paths: ['tests']
snapshot-paths: ['snapshots']
macro-paths: ['macros']

clean-targets:
  - target
  - dbt_packages

models:
  sf_pipeline:

    staging:
      +materialized: view
      +schema: staging

    intermediate:
      +materialized: view
      +schema: intermediate

    marts:
      +materialized: table
      +schema: marts
