# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

env:
  DBT_PROFILES_DIR: '{{.TASKFILE_DIR}}'

tasks:

  format:
    cmd: sqruff fix -f human macros/ models/ tests/

  lint:
    cmd: sqruff lint -f human models/ macros/ tests/

  compile:
    cmd: dbt compile

  run:
    cmd: dbt run

  debug:
    cmd: dbt debug
