CREATE TABLE IF NOT EXISTS LANDING.CUSTOMERS (
    CUSTOMERID VARCHAR(100) PRIMARY KEY,
    COMPANYNAME VARCHAR(150),
    CONTACTNAME VARCHAR(150),
    CONTACTTITLE VARCHAR(150),
    ADDRESS VARCHAR(150),
    CITY VARCHAR(150),
    REGION VARCHAR(150),
    POSTALCODE VARCHAR(150),
    COUNTRY VARCHAR(150),
    PHONE VARCHAR(150),
    FAX VARCHAR(150)
);
