CREATE TABLE IF NOT EXISTS LANDING.ORDERS (
    ORDERID INTEGER PRIMARY KEY,
    CUSTOMERID VARCHAR(100),
    EMPLOYEEID INTEGER,
    ORDERDATE DATETIME,
    REQUIREDDATE DATETIME,
    SHIPPEDDATE DATETIME,
    SHIPVIA INTEGER,
    FREIGHT FLOAT,
    SHIPNAME VARCHAR(100),
    SHIPADDRESS VARCHAR(100),
    SHIPCITY VARCHAR(100),
    SHIPREGION VARCHAR(100),
    SHIPPOSTALCODE VARCHAR(100),
    SHIPCOUNTRY VARCHAR(100)
);
