CREATE TABLE IF NOT EXISTS LANDING.PRODUCTS (
    PRODUCTID INTEGER PRIMARY KEY,
    PRODUCTNAME VARCHAR(100),
    SUPPLIERID INTEGER,
    CATEGORYID INTEGER,
    QUANTITYPERUNIT VARCHAR(100),
    UNITPRICE FLOAT,
    UNITSINSTOCK INTEGER,
    UNITSONORDER INTEGER,
    REORDERLEVEL INTEGER,
    DISCONTINUED INTEGER
);
