CREATE TABLE IF NOT EXISTS LANDING.SUPPLIERS (
    SUPPLIERID INTEGER PRIMARY KEY,
    COMPANYNAME VARCHAR(100),
    CONTACTNAME VARCHAR(100),
    CONTACTTITLE VARCHAR(100),
    ADDRESS VARCHAR(200),
    CITY VARCHAR(100),
    REGION VARCHAR(100),
    POSTALCODE VARCHAR(100),
    COUNTRY VARCHAR(100),
    PHONE VARCHAR(100),
    FAX VARCHAR(100),
    HOMEPAGE VARCHAR(100)
);
