CREATE OR REPLACE PROCEDURE LANDING.LOAD_ALL()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CALL LANDING.LOAD_CATEGORIES();
    CALL LANDING.LOAD_REGIONS();
    CALL LANDING.LOAD_TERRITORIES();
    CALL LANDING.LOAD_SHIPPERS();
    CALL LANDING.LOAD_SUPPLIERS();
    CALL LANDING.LOAD_EMPLOYEES();
    CALL LANDING.LOAD_EMPLOYEE_TERRITORIES();
    CALL LANDING.LOAD_CUSTOMERS();
    CALL LANDING.LOAD_PRODUCTS();
    CALL LANDING.LOAD_ORDERS();
    CALL LANDING.LOAD_ORDER_DETAILS();

    RETURN 'Loaded all Northwind landing tables';
END;
$$;
