CREATE OR REPLACE PROCEDURE LANDING.LOAD_CATEGORIES()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    COPY INTO LANDING.CATEGORIES
    FROM
    (
        SELECT
            $1,
            $2,
            $3,
            $4
        FROM @LANDING.NORTHWIND_STAGE/categories.csv
    )
    ON_ERROR = abort_statement
    FILE_FORMAT = (FORMAT_NAME = LANDING.NORTHWIND_CSV_INGESTION_FORMAT);

    RETURN 'Loaded LANDING.CATEGORIES';
END;
$$;
