CREATE OR REPLACE PROCEDURE LANDING.LOAD_EMPLOYEE_TERRITORIES()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    COPY INTO LANDING.EMPLOYEE_TERRITORIES
    FROM
    (
        SELECT
            $1,
            $2
        FROM @LANDING.NORTHWIND_STAGE/"employee-territories.csv"
    )
    ON_ERROR = abort_statement
    FILE_FORMAT = (FORMAT_NAME = LANDING.NORTHWIND_CSV_INGESTION_FORMAT);

    RETURN 'Loaded LANDING.EMPLOYEE_TERRITORIES';
END;
$$;
