CREATE OR REPLACE PROCEDURE LANDING.LOAD_REGIONS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    COPY INTO LANDING.REGIONS
    FROM
    (
        SELECT
            $1,
            $2
        FROM @LANDING.NORTHWIND_STAGE/regions.csv
    )
    ON_ERROR = abort_statement
    FILE_FORMAT = (FORMAT_NAME = LANDING.NORTHWIND_CSV_INGESTION_FORMAT);

    RETURN 'Loaded LANDING.REGIONS';
END;
$$;
