CREATE OR REPLACE PROCEDURE LANDING.LOAD_SHIPPERS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    COPY INTO LANDING.SHIPPERS
    FROM
    (
        SELECT
            $1,
            $2,
            $3
        FROM @LANDING.NORTHWIND_STAGE/shippers.csv
    )
    ON_ERROR = abort_statement
    FILE_FORMAT = (FORMAT_NAME = LANDING.NORTHWIND_CSV_INGESTION_FORMAT);

    RETURN 'Loaded LANDING.SHIPPERS';
END;
$$;
