# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

dotenv:
  - .env

includes:
  tf:
    taskfile: ./infra/Taskfile.yml
    dir: ./infra


tasks:
  env:
    cmd: printenv
