CREATE OR REPLACE TABLE NORTHWIND_DEV.LANDING.CATEGORIES (
    CATEGORYID INTEGER PRIMARY KEY,
    CATEGORYNAME VARCHAR(100),
    DESCRIPTION STRING,
    PICTURE STRING
);


COPY INTO NORTHWIND_DEV.LANDING.CATEGORIES
FROM
(
    SELECT
        $1,
        $2,
        $3,
        $4
    FROM @NORTHWIND_DEV.LANDING.NORTHWIND_STAGE/categories.csv
)
ON_ERROR = abort_statement
FILE_FORMAT = (FORMAT_NAME = NORTHWIND_DEV.LANDING.NORTHWIND_CSV_INGESTION_FORMAT);
