CREATE OR REPLACE TABLE NORTHWIND_DEV.LANDING.CUSTOMERS (
    CUSTOMERID VARCHAR(100) PRIMARY KEY,
    COMPANYNAME VARCHAR(150),
    CONTACTNAME VARCHAR(150),
    CONTACTTITLE VARCHAR(150),
    ADDRESS VARCHAR(150),
    CITY VARCHAR(150),
    REGION VARCHAR(150),
    POSTALCODE VARCHAR(150),
    COUNTRY VARCHAR(150),
    PHONE VARCHAR(150),
    FAX VARCHAR(150)
);


COPY INTO NORTHWIND_DEV.LANDING.CUSTOMERS
FROM
(
    SELECT
        $1,
        $2,
        $3,
        $4
    FROM @NORTHWIND_DEV.LANDING.NORTHWIND_STAGE/customers.csv
)
ON_ERROR = abort_statement
FILE_FORMAT = (FORMAT_NAME = NORTHWIND_DEV.LANDING.NORTHWIND_CSV_INGESTION_FORMAT);
