CREATE OR REPLACE TABLE NORTHWIND_DEV.LANDING.EMPLOYEE_TERRITORIES (
    EMPLOYEEID INTEGER PRIMARY KEY,
    TERRITORYID INTEGER

);


COPY INTO NORTHWIND_DEV.LANDING.EMPLOYEE_TERRITORIES
FROM
(
    SELECT
        $1,
        $2
    FROM @NORTHWIND_DEV.LANDING.NORTHWIND_STAGE/"employee-territories.csv"
)
ON_ERROR = abort_statement
FILE_FORMAT = (FORMAT_NAME = NORTHWIND_DEV.LANDING.NORTHWIND_CSV_INGESTION_FORMAT);
