CREATE OR REPLACE TABLE NORTHWIND_DEV.LANDING.ORDER_DETAILS (
    ORDERID INTEGER PRIMARY KEY,
    PRODUCTID INTEGER,
    UNITPRICE FLOAT,
    QUANTITY INTEGER,
    DISCOUNT FLOAT
);


COPY INTO NORTHWIND_DEV.LANDING.ORDER_DETAILS
FROM
(
    SELECT
        $1,
        $2,
        $3,
        $4,
        $5
    FROM @NORTHWIND_DEV.LANDING.NORTHWIND_STAGE/"order-details.csv"
)
ON_ERROR = abort_statement
FILE_FORMAT = (FORMAT_NAME = NORTHWIND_DEV.LANDING.NORTHWIND_CSV_INGESTION_FORMAT);
