CREATE OR REPLACE TABLE NORTHWIND_DEV.LANDING.PRODUCTS (
    PRODUCTID INTEGER PRIMARY KEY,
    PRODUCTNAME VARCHAR(100),
    SUPPLIERID INTEGER,
    CATEGORYID INTEGER,
    QUANTITYPERUNIT VARCHAR(100),
    UNITPRICE FLOAT,
    UNITSINSTOCK INTEGER,
    UNITSONORDER INTEGER,
    REORDERLEVEL INTEGER,
    DISCONTINUED INTEGER
);


COPY INTO NORTHWIND_DEV.LANDING.PRODUCTS
FROM
(
    SELECT
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10
    FROM @NORTHWIND_DEV.LANDING.NORTHWIND_STAGE/products.csv
)
ON_ERROR = abort_statement
FILE_FORMAT = (FORMAT_NAME = NORTHWIND_DEV.LANDING.NORTHWIND_CSV_INGESTION_FORMAT);
