CREATE OR REPLACE TABLE NORTHWIND_DEV.LANDING.REGIONS (
    REGIONID INTEGER PRIMARY KEY,
    DESCRIPTION VARCHAR(50)
);

COPY INTO NORTHWIND_DEV.LANDING.REGIONS
FROM
(
    SELECT
        $1,
        $2
    FROM @NORTHWIND_DEV.LANDING.NORTHWIND_STAGE/regions.csv
)
ON_ERROR = abort_statement
FILE_FORMAT = (FORMAT_NAME = NORTHWIND_DEV.LANDING.NORTHWIND_CSV_INGESTION_FORMAT);
