CREATE OR REPLACE TABLE NORTHWIND_DEV.LANDING.SHIPPERS (
    SHIPPERID INTEGER PRIMARY KEY,
    COMPANYNAME VARCHAR(50),
    PHONE VARCHAR(50)
);

COPY INTO NORTHWIND_DEV.LANDING.SHIPPERS
FROM
(
    SELECT
        $1,
        $2,
        $3
    FROM @NORTHWIND_DEV.LANDING.NORTHWIND_STAGE/shippers.csv
)
ON_ERROR = abort_statement
FILE_FORMAT = (FORMAT_NAME = NORTHWIND_DEV.LANDING.NORTHWIND_CSV_INGESTION_FORMAT);
