CREATE OR REPLACE TABLE NORTHWIND_DEV.LANDING.SUPPLIERS (
    SUPPLIERID INTEGER PRIMARY KEY,
    COMPANYNAME VARCHAR(100),
    CONTACTNAME VARCHAR(100),
    CONTACTTITLE VARCHAR(100),
    ADDRESS VARCHAR(200),
    CITY VARCHAR(100),
    REGION VARCHAR(100),
    POSTALCODE VARCHAR(100),
    COUNTRY VARCHAR(100),
    PHONE VARCHAR(100),
    FAX VARCHAR(100),
    HOMEPAGE VARCHAR(100)
);


COPY INTO NORTHWIND_DEV.LANDING.SUPPLIERS
FROM
(
    SELECT
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12
    FROM @NORTHWIND_DEV.LANDING.NORTHWIND_STAGE/suppliers.csv
)
ON_ERROR = abort_statement
FILE_FORMAT = (FORMAT_NAME = NORTHWIND_DEV.LANDING.NORTHWIND_CSV_INGESTION_FORMAT);
