# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  format:
    cmd: sqruff fix -f human --dialect snowflake .

  lint:
    cmd: sqruff lint -f human --dialect snowflake .
