CREATE OR REPLACE TABLE NORTHWIND_DEV.LANDING.TERRITORIES (
    TERRITORYID INTEGER PRIMARY KEY,
    DESCRIPTION VARCHAR(50),
    REGIONID INTEGER
);

COPY INTO NORTHWIND_DEV.LANDING.TERRITORIES
FROM
(
    SELECT
        $1,
        $2,
        $3
    FROM @NORTHWIND_DEV.LANDING.NORTHWIND_STAGE/territories.csv
)
ON_ERROR = abort_statement
FILE_FORMAT = (FORMAT_NAME = NORTHWIND_DEV.LANDING.NORTHWIND_CSV_INGESTION_FORMAT);
