# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  init:
    desc: no description available
    cmd: terraform init -backend=false

  validate:
    desc: no description available
    cmd: terraform validate

  format:
    desc: no description available
    cmd: terraform fmt -recursive
