SELECT
    EMPLOYEEID      AS "EMPLOYEE_ID",
    LASTNAME        AS "LAST_NAME",
    FIRSTNAME       AS "FIRST_NAME",
    TITLE           AS "JOB_TITLE",
    TITLEOFCOURTESY AS "TITLE_OF_COURTESY",
    BIRTHDATE       AS "BIRTH_DATE",
    HIREDATE        AS "HIRE_DATE",
    ADDRESS,
    CITY,
    REGION,
    POSTALCODE      AS "POSTAL_CODE",
    COUNTRY,
    HOMEPHONE       AS "HOME_PHONE",
    EXTENSION       AS "EXT",
    PHOTO,
    NOTES,
    REPORTSTO       AS "REPORTS_TO",
    PHOTOPATH       AS "PHOTO_PATH"

FROM {{ source('northwind', 'employees') }}
