SELECT
    SUPPLIERID   AS SUPPLIER_ID,
    COMPANYNAME  AS COMPANY_NAME,
    CONTACTNAME  AS CONTACT_NAME,
    CONTACTTITLE AS CONTACT_TITLE,
    ADDRESS,
    CITY,
    REGION,
    POSTALCODE   AS POSTAL_CODE,
    COUNTRY,
    PHONE,
    FAX,
    HOMEPAGE

FROM {{ source('northwind', 'suppliers') }}
