SELECT
    PRODUCTID       AS PRODUCT_ID,
    PRODUCTNAME     AS PRODUCT_NAME,
    SUPPLIERID      AS SUPPLIER_ID,
    CATEGORYID      AS CATEGORY_ID,
    QUANTITYPERUNIT AS QUANTITY_PER_UNIT,
    UNITPRICE       AS UNIT_PRICE,
    UNITSINSTOCK    AS UNITS_IN_STOCK,
    UNITSONORDER    AS UNITS_ON_ORDER,
    REORDERLEVEL    AS REORDER_LEVEL,
    DISCONTINUED

FROM {{ source('northwind', 'products') }}
