name: Infrastructure CI

on:
  push:
    paths:
      - infra/**
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  fmt:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform fmt
        working-directory: infra
        run: terraform fmt -check -recursive -diff

  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform init
        working-directory: infra
        run: terraform init -backend=false

      - name: terraform validate
        working-directory: infra
        run: terraform validate

  plan:
    name: Plan
    needs: [fmt, validate]
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}
          aws-profile: tf-manager

      - run: |
          # Check caller identity for dev account
          aws sts get-caller-identity --profile tf-manager

      - name: terraform init
        working-directory: infra
        run: terraform init
